### ISSUE TITLE
[Feature] 리워드

### ISSUE THREAD

**Issue by pingowl** [DropDrugs/BE_dd#5]
## 🔨 Describe
- 리워드 포인트 지급, 사용 기능 구현

## ✅ Tasks
- [ ] 리워드 지급 기능
- [ ] 리워드 총점 조회
- [ ] 리워드 기록 조회
